services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATRABASE: database
    ports:
      - 5432:5432

  server:
    container_name: server
    restart: always
    build: "."
    depends_on:
      - database
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/var/www/app
